### ISSUE TITLE
Using test command againt an MQTT3 only broker

### ISSUE THREAD

**Issue by MicWalter** [hivemq/mqtt-cli#144]
If I use mqtt test against an broker that only supports MQTT3 (i.e. HiveMQ 3) an exception is logged in the MQTT 5 output.

## Expected behavior
```MQTT 5: NO```

## Actual behavior
```
MQTT 5: Could not connect MQTT5 client: com.hivemq.client.mqtt.mqtt5.exceptions.Mqtt5DisconnectException: Exception while decoding CONNACK: remaining length too short
	at com.hivemq.client.internal.mqtt.MqttBlockingClient.connect(MqttBlockingClient.java:91)
	at com.hivemq.client.mqtt.mqtt5.Mqtt5BlockingClient.connect(Mqtt5BlockingClient.java:64)
	at com.hivemq.cli.mqtt.test.Mqtt5FeatureTester.testConnect(Mqtt5FeatureTester.java:87)
	at com.hivemq.cli.commands.cli.TestBrokerCommand.testMqtt5Features(TestBrokerCommand.java:143)
	at com.hivemq.cli.commands.cli.TestBrokerCommand.run(TestBrokerCommand.java:127)
	at picocli.CommandLine.executeUserObject(CommandLine.java:1729)
	at picocli.CommandLine.access$900(CommandLine.java:145)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2101)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2068)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:1935)
	at picocli.CommandLine.execute(CommandLine.java:1864)
	at com.hivemq.cli.MqttCLIMain.main(MqttCLIMain.java:61)
Caused by: com.hivemq.client.mqtt.exceptions.MqttDecodeException: Exception while decoding CONNACK: remaining length too short
NO
```

### Steps
* start HiveMQ 3
* let mqtt test run against it

## Details
- Affected MQTT CLI version(s): 
- Used JVM version:

**Comment by ckrey** [comment]
In general `test` command logs exceptions rather than simple error messages like the `sub` command:

```
% mqtt sub -t 'abc' -V 3
Connection refused: localhost/127.0.0.1:1883
```

```
% mqtt test -V 3
MQTT 3: Could not connect MQTT3 client: java.util.concurrent.ExecutionException: com.hivemq.client.mqtt.exceptions.ConnectionFailedException: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: localhost/127.0.0.1:1883
	at java.base/java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:395)
	at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2022)
...
```
